package pakage1;

public class Assignment_61 {

	public static void main(String[] args) {
		 try {
		int a =10;
		int b=0;
		int c=a/b;
		System.out.println(c);

	}
		 catch(ArithmeticException a1) {
			 
			 System.out.println("Handle the exception in catch block");
		 }
			 
		 }

}

